### ISSUE TITLE
[Doc] install kubewharf enhanced kubernetes: wget https://github.com/containerd/containerd/releases/download/v1.4.12/containerd-1.6.9-linux-amd64.tar.gz not found

### ISSUE THREAD

**Issue by zhy76** [kubewharf/katalyst-core#148]
### What happened?

When I follow the [documentation](https://github.com/kubewharf/katalyst-core/blob/main/docs/install-enhanced-k8s.md) to install kubewharf enhanced kubernetes, I found this:
![image](https://github.com/kubewharf/katalyst-core/assets/56665618/dc427bfa-e506-4444-9112-d62aee5a2841)

Looks like `wget https://github.com/containerd/containerd/releases/download/v1.4.12/containerd-1.6.9-linux-amd64.tar.gz` already can't find, maybe need to update the relevant documentation.

### What did you expect to happen?

update the relevant documentation

### How can we reproduce it (as minimally and precisely as possible)?

wget https://github.com/containerd/containerd/releases/download/v1.4.12/containerd-1.6.9-linux-amd64.tar.gz

### Software version

<details>

```console
$ <software> version
# paste output here
```
</details>

**Comment by pendoragon** [comment]
Good catch, thanks! I have sent a PR to fix the link
