### ISSUE TITLE
Support for OOM priority as a QoS enhancement

### ISSUE THREAD

**Issue by caohe** [kubewharf/katalyst-core#216]
### What would you like to be added?

- Users can specify the OOM priority as a QoS enhancement.
- Implement OOM priority with `oom_score_adj`.

### Why is this needed?

Currently, Kubernetes will configure different `oom_score_adj` values for different QoS classes. However, the order of OOM also depends on other dimensional factors such as the memory usage of the container. 

In the colocation scenario, it's important to strictly ensure that web services are terminated later than batch jobs due to OOM when the cluster's memory resources become scarce.

**Comment by y-ykcir** [comment]
@caohe Hi, I am very interested in this issue, is there any chance to participate now?
