### ISSUE TITLE
Support NUMA-granularity reporting for reclaimed resources

### ISSUE THREAD

**Issue by caohe** [kubewharf/katalyst-core#217]
### What would you like to be added?

Enhance the resource reporting mechanism to support reporting of reclaimed resources at the granularity of NUMA nodes.

### Why is this needed?

Currently, the reporting of reclaimed resources is performed at a node granularity level. However, in environments with NUMA architectures, this approach might lead to suboptimal scheduling result and potential pod evictions due to NUMA-level interference.

**Comment by Lan-ce-lot** [comment]
@caohe Hi, I am very interested in this issue. I'm new in kubewharf, may i ask you for more infomation?

**Comment by caohe** [comment]
> @caohe Hi, I am very interested in this issue. I'm new in katalyst, may i ask you for more infomation?

@Lan-ce-lot Yes, we can discuss this at the community meeting today. Please feel free to edit the agenda
https://bytedance.feishu.cn/docx/VXGfdiddUoemoQx54uacwSHonPd
