### ISSUE TITLE
katalyst-agent: get reclaimed resource.katalyst.kubewharf.io/reclaimed_memory capacity failed: resource memory last report value not found

### ISSUE THREAD

**Issue by zhy76** [kubewharf/katalyst-core#240]
### What happened?

![image](https://github.com/kubewharf/katalyst-core/assets/56665618/9b5a1b9c-7cab-467e-8894-a361aa6a99f0)

### What did you expect to happen?

GetReportContentResponse from headroom-reporter-plugin Endpoint success.

### How can we reproduce it (as minimally and precisely as possible)?

Use the image of the latest main branch

### Software version

<details>

```console
$ <software> version
# paste output here
```
</details>

**Comment by caohe** [comment]
@zhy76 Does this error appear within two minutes after starting? cc @luomingmeng

**Comment by zhy76** [comment]
> @zhy76 Does this error appear within two minutes after starting? cc @luomingmeng

No, This error persists in the katalyst-agent log after startup

**Comment by zhy76** [comment]
It seems that the version of v0.3.1 does not have this error, but the latest version of the main branch does.

**Comment by zhy76** [comment]
This issue is due to malachite not being deployed, which can be fixed by `helm install malachite -n malachite-system --create-namespace kubewharf/malachite`, I will close this.
