### ISSUE TITLE
memory advisor sendAdvices channel sometimes full

### ISSUE THREAD

**Issue by zhy76** [kubewharf/katalyst-core#241]
### What happened?

![image](https://github.com/kubewharf/katalyst-core/assets/56665618/26d1c6f2-d42b-42a4-9f91-abeeaa5c27d7)

Maybe we need Increase capacity of sendChan
https://github.com/kubewharf/katalyst-core/blob/6085babd494dd04abfa770292a3aeac9dda61ab9/pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go#L89

### What did you expect to happen?

no error

### How can we reproduce it (as minimally and precisely as possible)?

get agent log

### Software version

<details>

```console
$ <software> version
# paste output here
```
</details>

**Comment by cheney-lin** [comment]
How often does this issue occur？

**Comment by zhy76** [comment]
It's kind of common on my side

**Comment by cheney-lin** [comment]
Actually, memory server will send response to qrm plugin when get advisorResp from memory advisor. If the channel is full, it indicates that the QRM plugin is overwhelmed with processing the results pushed by the memory server. If we simply increase the capacity of the channel, it will result in sending some outdated recommendation results to the QRM plugin, which is undesirable. Can we check if there are any abnormalities on the QRM side?

**Comment by zhy76** [comment]
I found qrm with these error:
![image](https://github.com/kubewharf/katalyst-core/assets/56665618/5e6b0401-0b9b-4949-9c03-2dd96c3de202)
![image](https://github.com/kubewharf/katalyst-core/assets/56665618/5c34ca36-a5bb-4b3d-bcbd-bcaf66fa9073)
