### ISSUE TITLE
code comments link address 😂

### ISSUE THREAD

**Issue by wanglei4687** [kubewharf/katalyst-core#295]
## Description：

code comments: 

https://github.com/kubewharf/katalyst-core/blob/650ae570146df55529959179487243f5d2803a45/cmd/base/healthz.go#L60C53-L60C53

linked with a PersistentVolumeSource struct.

## Question:

In my opinion, It may link with readiness information. Is it right?😁

**Comment by waynepeking348** [comment]
yeah, you can submit a new pr to solve this

**Comment by caohe** [comment]
@wanglei4687 Could you help fix this link?

**Comment by wanglei4687** [comment]
> @wanglei4687 Could you help fix this link?

ok, I will do it.
